### ISSUE TITLE
Anti-aliasing of font seems to get disabled within an `inverseFlipId` component

### ISSUE THREAD

**Issue by loganpowell** [aholachek/react-flip-toolkit#89]
Hi there!

Just wanted to say that I love this library. I can't believe how hard it is to find a simple "magic move" component that just works as does this one. Thank you.

This might be  a minor issue, so no big deal, but I can't figure out a way to preserve anti-aliasing removal during the animation.

Here is an example:

https://loganpowell.github.io/next-themed-magic-components

This works flawlessly in Edge (antialiasing is preserved during animation), but in Chrome antialiasing is not being applied at all and in Firefox, there's a flash of aliasing of the font

Here's my current `<head>` css:

```css
html {
            -webkit-font-smoothing: antialiased;  /* anti-aliasing Chrome/Safari/Webkit */
            -webkit-font-rendering: antialiased; /* font anti-aliasing Chrome/Safari/Webkit */
            -moz-osx-font-smoothing: antialiased; /* anti-aliasing Firefox */
            font-smoothing: antialiased;
            box-sizing: border-box; /* box-sizing  */
          }
          *, *::before, *::after {
            box-sizing: inherit; /* make it easier to change the box-sizing of components */
          }
          @-moz-document url-prefix() { /* Disable scrollbar Firefox */
            html{
              scrollbar-width: none;
            }
          }
          body {
            margin: 0; /* remove default margin */
            scrollbar-width: none; /* Also needed to disable scrollbar Firefox */
            -ms-overflow-style: none;  /* Disable scrollbar IE 10+ */
          }
          body::-webkit-scrollbar {
            width: 0px;
            background: transparent; /* Disable scrollbar Chrome/Safari/Webkit */
          }
```

**Comment by loganpowell** [comment]
I think I found a related SO thread:
https://stackoverflow.com/questions/15464055/css-transition-effect-makes-image-blurry-moves-image-1px-in-chrome

**Comment by loganpowell** [comment]
I think I found a fix, in the `<head><style>...` I got the flicker of blur during animation to go away using:

```css
html {
  filter: blur(0);
  -webkit-filter: blur(0);
}
```
